### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by phanchidan-2**
Would like you to integrate these modifications. Thanks.

### CODE REVIEW

**Comment by phanchidan** [comment]
Could you explain a bit more?

**Comment by phanchidan** [comment]
Well, I improved a few sentences.

**Comment by phanchidan-2** [comment]
Well, I did my best

**Comment by phanchidan** [comment]
OK fine I'll merge it! Thanks.

Le 2 mars 2017 7:11 AM, "Guillaume Phan (ALT)" <notifications@github.com> a
écrit :

Well, I did my best

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/phanchidan/sample-git-1/pull/3#issuecomment-283679834>,
or mute the thread

**Pull request merged**
